version: '3.1'
services:
  client:
    build: ./Dashboard
    ports:
    - 19006:19006
    command: ["npm", "run", "web", "--tunnel"]
  db:
    build: ./db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: test
#      MYSQL_USER: mysql
#      MYSQL_PASSWORD: test
#      MYSQL_DATABASE: mydb
#    volumes:
#    - /opt/mysql_data:/var/lib/mysql
    ports:
    - 3306:3306
    networks:
    - backend
  sv:
    build: ./Dashboard/Server
    links:
    - db
    environment:
      DATABASE_HOST: db
#      MYSQL_USER: mysql
#      MYSQL_PASSWORD: supersecret
    ports:
    - 8080:8080
    networks:
    - backend

networks:
  backend: